import './globals.css'

import 'bootstrap/dist/css/bootstrap.min.css';
import '../../public/assets/fonts/fonts.css'


export const metadata = {
  title: 'E.B Real Estate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
